### ISSUE TITLE
Game crashes when fishing

### ISSUE THREAD

**Issue by ech0-null** [HerrahStrings/packwiz-packs#13]
I'm not very knowledgeable so sorry, but my game crashes everytime I use a fishing rod. I tried a fresh install without the extra mods I was using and faced the same problem. I'm using TQuilt 3.5.3 on Prism Launcher

**Comment by wrathful-titaness** [comment]
[crash-2023-04-02_21.37.48-server.txt](https://github.com/sisby-folk/mc-packs/files/11133957/crash-2023-04-02_21.37.48-server.txt)

**Comment by sleepingdragoninn** [comment]
Thanks for the report! We recently swapped to using [Fishing Real](https://modrinth.com/mod/fishing-real) instead of an older fork of realistic fishing - we'll confirm this is the issue, report it, and swap back if need be.

Feel free to swap it yourself if need be! [realistic fishing](https://modrinth.com/mod/fishing)

**Comment by sleepingdragoninn** [comment]
Update! seems like this is actually due to the 1.18.2 version of dyable fishing lines being installed, which is.. wrong. We'll update it if we get access to the source, but it's currently not available.

**Comment by sleepingdragoninn** [comment]
Oh right yeah we fixed this oops

**Comment by wrathful-titaness** [comment]
thanks you :)
