### ISSUE TITLE
Specific mob toggling for phobias

### ISSUE THREAD

**Issue by emifloofy** [HerrahStrings/packwiz-packs#19]
There are some mobs in vanilla minecraft that can trigger certain phobias or trauma responses, and it would be a good idea to add a way to toggle these mobs.

Namely:
- Spiders (Arachnophobia)
- Endermen (Anxiety from being yelled at)

**Comment by sleepingdragoninn** [comment]
We'd love to put this in - I think this is best achieved using added gamerules, and [VanillaDisable](https://modrinth.com/mod/vanilla-disable) seems like it would be best to achieve just that!

For now feel free to install the mod yourself and use the `endermenEnabled`, `spidersEnabled` and `caveSpidersEnabled` gamerules - string can be broken from wool, and ender pearls can come from trading. I'll leave this issue open until we've implemented and documented this in a satisfactory way, but it might end up on the backburner for a bit so I strongly encourage players and server owners to pick this one up if needed!

**Comment by DragonEggBedrockBreaking** [comment]
Hi, I'm the developer of VanillaDisable. I just wanted to let you (and therefore all users who you've recommended this mod to) know that the latest version of this mod (v3.0.0) rewrites the entire config system and uses something custom, rather than gamerules. These gamerules should be migrated, but the migration system isn't perfect. Here's how you disable entities' existence in the new version:

`/vd rule entities minecraft:<entityName> other enabled false`

or you can use the in-game gui, which you open with the hotkey `k`. Thank you for recommending my mod to your users!

**Comment by sleepingdragoninn** [comment]
thanks for the extra info! that change probably makes a lot of sense of the implmentation side I imagine ahahah - I'll keep the mod on our radar when we're scoping out 1.20 plans!

**Comment by sleepingdragoninn** [comment]
going to close this as the pack description has an explicit recommendation
